version: '3'
services: 
    core_api:
        build: ./app/backend      
        command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
        ports: 
            - "8000:8000"
        volumes: 
            - ./app/:/app/